.PHONY: typeset

typeset:
	pandoc                          \
	  --from         markdown       \
	  --to           latex          \
	  --template     template.tex   \
	  --out          bridges.pdf \
	  --pdf-engine xelatex        \
	  bridges.md
